"""Add personas table

Revision ID: e84a87a1efe7
Revises: 633bb6dfd897
Create Date: 2026-06-17 20:25:45.717912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e84a87a1efe7"
down_revision: Union[str, Sequence[str], None] = "633bb6dfd897"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("system_prompt", sa.String(), nullable=False),
        sa.Column("personality_traits", sa.JSON(), nullable=True),
        sa.Column("speaking_style", sa.String(), nullable=True),
        sa.Column("goals", sa.String(), nullable=True),
        sa.Column("constraints", sa.String(), nullable=True),
        sa.Column("domain_expertise", sa.String(), nullable=True),
        sa.Column("voice", sa.String(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personas")
    # ### end Alembic commands ###
